#!/usr/bin/env bash

# """Copy of GenAI-ML-HW8-Fine-tuning_Leads_to_Forgetting.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1HeUwzHl-pdjNisoYAavYJthO0D2808vn

# # ML2025 Homework 8 - Fine-tuning Leads to Forgetting

# This notebook is for GenAI-ML 2025 Homework 8, focusing on the problem of fine-tuning leading to forgetting. The goal is to fine-tune a model using the GSM8K dataset while observing the effects on previously learned knowledge about safeness.

# **Credit** : [ML2025 HW6 Colab Sample Code](https://colab.research.google.com/drive/1sXopMDAT0nRrOTL52ECSPV07gKNoDn7n)

# ## Check GPU
# """

# !nvidia-smi

# """## Download Dataset & Install Packages"""

# !wget https://www.csie.ntu.edu.tw/~b10902031/gsm8k_train.jsonl # original dataset for fine-tuning
# !wget https://www.csie.ntu.edu.tw/~b10902031/gsm8k_train_self-instruct.jsonl # part of fine-tuning dataset refined by llama-3.2-1b-instruct
# !wget https://www.csie.ntu.edu.tw/~b10902031/gsm8k_test_public.jsonl # gsm8k public test dataset
# !wget https://www.csie.ntu.edu.tw/~b10902031/gsm8k_test_private.jsonl # gsm8k private test dataset
# !wget https://www.csie.ntu.edu.tw/~b10902031/ailuminate_test.csv # ailuminate test dataset (public + private)

# # !pip install -U datasets trl bitsandbytes transformers accelerate peft

# """## Huggingface Login

# ### Huggingface token 取得說明請參考以下投影片以及說明影片
# [Huggingface token 投影片連結](https://speech.ee.ntu.edu.tw/~hylee/ml/ml2025-course-data/hw6_model.pdf)

# [Huggingface token 說明影片連結](https://youtube.com/watch?v=b8fad34gpFY&feature=youtu.be)
# """

# """## Import Packages"""




# Shell script

set -euo pipefail

# 1) Check GPU
command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi || echo "nvidia-smi not found."

# 2) Download datasets (skip if already downloaded)
base="https://www.csie.ntu.edu.tw/~b10902031"
files=(
  "gsm8k_train.jsonl"
  "gsm8k_train_self-instruct.jsonl"
  "gsm8k_test_public.jsonl"
  "gsm8k_test_private.jsonl"
  "ailuminate_test.csv"
)

for f in "${files[@]}"; do
  if [[ -f "$f" ]]; then
    echo "Already have $f (skipping)"
  else
    echo "Downloading $f..."
    wget -q --show-progress "${base}/${f}"
  fi
done

# 3) (Optional) install packages
# python -m pip install -U datasets trl bitsandbytes transformers accelerate peft

# 4) Hugging Face login (recommended: use env var)
# Export your token in your shell before running:
#   export HF_TOKEN="hf_...."
if [[ -n "${HF_TOKEN:-}" ]]; then
  huggingface-cli login --token "$HF_TOKEN"
else
  echo "HF_TOKEN not set. To login:"
  echo '  export HF_TOKEN="hf_..."'
  echo "  ./setup.sh"
  echo "Or run: huggingface-cli login"
fi